### ISSUE TITLE
elasticsearch ping caused variable view to disappear

### ISSUE THREAD

**Issue by FelixBenning** [ManuelHentschel/VSCode-R-Debugger#78]
# Reproduction

use this command

```R
es_conn <- elastic::connect(host = 'db', port = 9200, errors = "complete")
es_conn$ping()
```

where `db` is the service name of an elasticsearch container [elasticsearch:7.8.1](https://hub.docker.com/_/elasticsearch)

i.e. (untested minimum working example docker-compose):

```yml
version: "3.8"
services:
    app:
        image: rocker/r-ver:4.0.0
        depends_on:
            - db
    db:
        image: elasticsearch:7.8.1
        environment: # environment variable inside container
            # elasticsearch single-node mode:
            - discovery.type=single-node
        volumes:
            - data:/usr/share/elasticsearch/data
            - 9200
volumes:
    data:
        driver: local
```

# Effect

variables disappear from viewer in the left panel, but they are still accessible from the debugger console
